name: Sync Quotes

on:
  discussion:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch only Quotes category
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql -f query='
          {
            repository(owner: "prabhatre", name: "prabhatre.github.io") {
              discussions(first: 100, categoryId: "DIC_kwDORBsRQ84C23y1", orderBy: {field: CREATED_AT, direction: DESC}) {
                nodes {
                  number
                  title
                  bodyText
                  author { login avatarUrl }
                }
              }
            }
          }' > raw.json

      - name: Convert to site JSON
        run: |
          jq '.data.repository.discussions.nodes' raw.json > quotes.json

      - name: Commit updated quotes
        run: |
          git config user.name "quotes-bot"
          git config user.email "bot@users.noreply.github.com"
          git add quotes.json
          git commit -m "update quotes" || echo "no changes"
          git push